### PR TITLE
Also applicable to CM13

### PR DESCRIPTION
**Pull request by ericfrs**

### CODE REVIEW

**Comment by chil360** [comment]
libnetcmdiface does not exist in SlimLP or CM13.
I have found it in CM11: https://github.com/CyanogenMod/android_hardware_broadcom_wlan/blob/cm-11.0/bcmdhd/bcmdhd_net_iface/Android.mk#L26
It's a lib for Broadcom but our wifi is Atheros. How can using this lib help?

**Comment by srfarias** [comment]
Yeah, also debug sf hw don't make anything with a defined composition on Y300. Sorry, i do this in my tablet and i confuse the files with other from an Htc device. 

The changes on Cyanogenmod already fixed the wifi issues (upload transfers, reboots with tether enabled..etc) on Y300..

I'll push now the right changes.

**Comment by chil360** [comment]
Which changes on CM have fixed the wifi issues?

**Comment by srfarias** [comment]
Really i don't know what exactly changes was.. I talked it with the Rremix team when i start to compile it. With the last 5.5.8 version that i compile all the wifi issues was fixed. It wasn't the only device that have this issue..same with blackscreen

And there's nothing related to RRemix changes. So.. 

Anyway, i make other pull, with the right changes.

**Comment by srfarias** [comment]
Has Slimlp the wifi issues ?

**Pull request closed without merging**
